# archived/webui:
# backport/1.6:
# backport/1.7:
# backport/1.8:
# beta/1.8:
# blocks-release:
# crash:
# do-not-merge:
# help-wanted:
# needs-discussion:
# needs-investigation:
# post-beta:
# pr/dependencies:
# pr/needs-rebase:
# pr/needs-tests:
theme/acls:
    - '(acl|ACL)'
# theme/agent-cache:
# theme/api:
theme/catalog:
    - '(catalog|Catalog)'
theme/certificates:
    - '(certificate|CA|Certificate\sAuthority)'
theme/cli:
    - '(command-line|commandline|cli|command)'
theme/config:
    - '(configuration_files|options#configuration_files)'
theme/connect:
    - '(Connect|connect|service\smesh|mesh|proxy|gateway)'
theme/consul-nomad:
    - '(nomad|Nomad)'
theme/consul-vault:
    - '(vault|Vault)'
# theme/contributing:
theme/dns:
    - '(dns|DNS)'
theme/envoy/xds:
    - '(envoy|xds|xDS|XDS|Envoy)'
theme/federation-usability:
    - '(WAN|wan|wan_fed|federation|fed)'
# theme/go-modules:
theme/health-checks:
    - '(health-check|healthcheck|health\scheck)'
theme/ingress-gw:
    - '(ingress|ingress-gateway|Ingress)'
# thementernal-cleanup:
theme/internals:
    - '(raft|RAFT|SERF|serf|lifeguard|Lifeguard|gossip)'
theme/kubernetes:
    - '(kubernetes|k8s|helm)'
theme/mesh-gw:
    - 'mesh'
# theme/operator-usability:
theme/performance:
    - 'performance'
theme/service-metadata:
    - 'meta-data'
theme/streaming:
    - 'stream'
theme/telemetry:
    - '(circonis|datadog|DataDog|prometheus|metric)'
theme/terminating-gw:
    - 'terminating'
theme/testing:
    - '(unit\stest|functional\stest|integration\stest|e2e|E2E)'
theme/tls:
    - '(mtls|mTLS|tls|TLS)'
theme/ui:
    - '(ui|browser|chrome|firefox|IE|ie|Chrome)'
theme/windows:
    - '(windows|Windows|Microsoft|microsoft)'
# thinking:
# type/bug:
type/ci:
    - '(circle|circleci)'
# type/crash:
type/docs:
    - '(docs\/|docs)'
# type/docs-cherrypick:
type/enhancement:
    - '(new\sfeature|feature)'
# type/good-first-issue:
# type/question:
# type/umbrella-☂️:
# version/0.8.3:
# waiting-pr-merge:
# waiting-reply:
# waiting-reply-🤖: